version : '3'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=mysql
      - DB_USER=Ravikant
      - DB_PASSWORD=123456
      - DB_NAME=schoolDB
    depends_on:
      - mysql
    restart: always
  
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: schoolDB

    volumes:
      - ./data:/var/lib/mysql
    restart: always

volumes:
  mysql_data: 